### ISSUE TITLE
Module not found: Error: Can't resolve 'react-with-important-style' i

### ISSUE THREAD

**Issue by ablankenship10** [brigand/react-with-important-style#1]
This is probably because your main file in package.json is set to lib/withImportantStyle.js but the actual should be src/withImportantStyle.js

It still doesn't work changing it to the src file. Not sure what jest is but you are setting that in package.json to ignore the lib directory. My install does not contain a lib directory at all (via yarn add react-with-important-style)

**Comment by brigand** [comment]
Thanks! Fixed and published as 0.2.2.

**Comment by ablankenship10** [comment]
Dude.. You should maintain every open source project with that speed haha.

Awesome, so its working now, but when I change my Div component to a DivImportant component with the library it doesn't render anything. Am I doing it wrong just adding:

`<DivImportant className={styles.popup} style={theme}>`

to my render function?

EDIT: fixed code rendering

**Comment by brigand** [comment]
Can you share the rest of your code for this file?

**Comment by ablankenship10** [comment]
```
imports : 

import React from "react";
import withImportantStyle from 'react-with-important-style';
import styles from "../style/styles.less";
const DivImportant = withImportantStyle('div');
const BtnImportant = withImportantStyle('button');
const InputImportant = withImportantStyle('input');


render function : 

const config   = this.props.config;
    const themeAll = {
      backgroundColor: config.background + ' !important',
      color: config.themeColor+ ' !important',
      borderColor: config.themeColor+ ' !important'
    };
    const theme    = {
      color: config.themeColor+ ' !important',
      borderColor: config.themeColor+ ' !important'
    };

return (
      <DivImportant className={styles.popup} style={themeAll}>
        <h1 className={styles.heading}>{config.heading}</h1>
        <div className={styles.body}>{config.body}</div>
        <DivImportant className={styles.bottom} style={theme}>
          <InputImportant type="email" className={styles.email_input} style={theme} placeholder="Email Address"
                 onChange={this.onChange.bind(this)}/>
          <BtnImportant className={styles.button} style={theme}
                  onClick={this.onSubmit.bind(this)}>{config.okButtonText}</BtnImportant>
          <BtnImportant className={styles.button} style={theme}
                  onClick={this.props.close}>{config.cancelButtonText}</BtnImportant>
        </DivImportant>
      </DivImportant>
    )
```

**Comment by brigand** [comment]
I tried it [here](https://codesandbox.io/s/lOxqN89g5) and it seems to be working.

**Comment by ablankenship10** [comment]
Odd, its completely not in the DOM at all for me. Let me make sure I don't have something else preventing rendering, but it worked fine just before I added this library.

**Comment by ablankenship10** [comment]
Oh man, sorry I'm an idiot. Rolled back the file before adding the library and it uncommented a line I remove for testing where I load a state from localstorage that prevents it from showing if it has before.

Thanks again for the swift fix! Its applying the styles now great
